name: Genify Battle Passcard Verification

on:
  pull_request:
    branches:
      - main

jobs:
  verify-genify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install ethers dotenv fs axios

      - name: Verify Genify Battle Passcard Ownership
        env:
          RPC_URL: "https://cloudflare-eth.com"
          GENIFY_CONTRACT: "0xfCDc908aecDaC96bcCc8B69002C907A01Bb554DB"
          TOKEN_ID: "3050309"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node verify-genify.js

      - name: Add Label for Verified Genify Holders
        if: success()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "Verified Genify Holder"

      - name: Send Telegram Alert
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d "chat_id=$TELEGRAM_CHAT_ID" \
          -d "text=✅ Verified Genify Battle Passcard Holder (#50309) has submitted a PR!"

      - name: Send Discord Alert
        if: success() && env.DISCORD_WEBHOOK_URL
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -s -X POST "$DISCORD_WEBHOOK_URL" \
          -H "Content-Type: application/json" \
          -d '{"content": "✅ Verified Genify Battle Passcard Holder (#50309) has submitted a PR!"}'
